const RATING_ALL = 'rating_all'
const RATING_POSITIVE = 'rating_positive'
const RATING_NEGATIVE = 'rating_negative'

const RATING_TYPE_ALL = -1
const RATING_TYPE_POSITIVE = 0
const RATING_TYPE_NEGATIVE = 1

export {
  RATING_ALL, RATING_POSITIVE, RATING_NEGATIVE,
  RATING_TYPE_ALL, RATING_TYPE_POSITIVE, RATING_TYPE_NEGATIVE
}
