export {default as Right} from '@ant-design/icons/lib/outline/RightOutline'
export {default as Star} from '@ant-design/icons/lib/outline/StarOutline'
export {default as Loading} from '@ant-design/icons/lib/outline/LoadingOutline'
export {default as PlusCircleFill} from '@ant-design/icons/lib/fill/PlusCircleFill'
export {default as MinusCircleFill} from '@ant-design/icons/lib/fill/MinusCircleFill'
export {default as Left} from '@ant-design/icons/lib/outline/LeftOutline'
export {default as ShoppingCart} from '@ant-design/icons/lib/outline/ShoppingCartOutline'